language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '7'

after_success: npm run coverage

deploy:
  provider: npm
  email: npm.bokub@mail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: 'node'
